---
title: "Cumulative Frequency Polygons"
author: "Ben Stano"
date: '2022-04-25'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(grid)
```

# Cumulative Percentage Polygon

```{r}
StatCPP <- ggproto("StatPercentile", Stat,
                          
  compute_group = function(data, scales) {
    data <- data.frame(y = data$x)
    new_data <- data.frame(y = apply(data, 2, function(x) ecdf(x)(sort(x))))
    new_data$x <- sort(data$y)
    new_data
  },
  
  required_aes = c("x")
  
)

stat_cumpp <- function(mapping = NULL, data = NULL, geom = "line",
                       position = "identity", na.rm = FALSE, show.legend = NA, 
                       inherit.aes = TRUE) {
  layer(
    stat = StatCPP, data = data, mapping = mapping, geom = geom, 
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm)
  )
}
```

```{r}
ggplot(mpg, aes(x = hwy)) +
  stat_cumpp()
```
# Percentile Summary Graph

How to add quantile lines

```{r}
StatPSG <- ggproto("StatPercentile", Stat,
                          
  compute_group = function(data, scales) {
    data <- data.frame(x = data$y)
    new_data <- data.frame(x = apply(data, 2, function(x) ecdf(x)(sort(x))))
    new_data$y <- sort(data$x)
    new_data
  },
  
  required_aes = c("y")
  
)

stat_persum <- function(mapping = NULL, data = NULL, geom = "point",
                       position = "identity", na.rm = FALSE, show.legend = NA, 
                       inherit.aes = TRUE) {
  layer(
    stat = StatPSG, data = data, mapping = mapping, geom = geom, 
    position = position, show.legend = show.legend, inherit.aes = inherit.aes,
    params = list(na.rm = na.rm)
  )
}
```

```{r}
ggplot(mpg, aes(y = hwy)) +
  stat_persum()
```

How to add these?

```{r}
quantile(mpg$hwy)
```